engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 500
ratings:
  paths:
  - server/**/*.js
  - server/*.js
  - client/src/
exclude_paths:
- node_modules/
- server/test/
- server/config
- docs/
- client/public/
