language: node_js
node_js:
  - "6.10.2"
branches:
  only:
    - master
install:
  - npm install
script:
  - npm test
cache:
  -npm install
services:
  - postgresql
before_script:
  - createuser postgres -s -U postgres
  - createdb postit_dev --username=postgres
  - sequelize db:migrate
after_success:
- npm run coveralls
after_script: 
  - nyc npm test && nyc report --reporter=text-lcov | coveralls