language: node_js
node_js:
  - "stable"
branches:
  only:
    - travis
install:
  - npm install
script:
  - npm test
cache:
  -npm install
services:
  - postgresql
before_script:
  - sequelize db:migrate
after_success:
- npm run coveralls
after_script: 
  - nyc npm test && nyc report --reporter=text-lcov | coveralls