language: node_js
node_js:
  - "stable"
branches:
  only:
    - travis
install:
  - npm install
script:
  - npm test
cache:
  -npm install
services:
  - postgresql
before_script:
  - createdb postit-dev --username=postgres
  - sequelize db:migrate
env:
  - MY_SUPER_SECRET='rgfiwa7t4873qr7tr87r8'
